# Práctica de Data Cleaning

In [1]:
import pandas as pd

## Objetivo

El objetivo de este ejercicio es aplicar técnicas de **limpieza de datos** en Pandas.

Este ejercicio cubre la manipulación de strings (utilizando métodos de strings), el uso de expresiones regulares, la importancia de la limpieza y la conversión a `datetime`

## Contexto del Conjunto de Datos

Hemos cargado un DataFrame que contiene información de Presidentes de EE. UU. La columna `'Born'` (Nacimiento) contiene la fecha y, entre paréntesis, la ciudad o ubicación, como por ejemplo: `February 22, 1732[b] (Westmoreland County, Virginia)`.

## Instrucciones

- De la columna `'President'` Crea una columna para el nombre 'firstname' y otra para el apellido (lastname) de los presidentes eliminando la referencias a las notas al pie que encuentres. Puedes utilizar un patron de Regular Expression para realizar esta tarea
- La columna `'Born'` contiene referencias entre corchetes (ej. `[b]`) y texto adicional entre paréntesis (ej. `(Westmoreland County, Virginia)`). Debemos eliminar todo este texto para quedarnos solo con la fecha limpia.
- Convierte la columna `'Born'` al Tipo `datetime`
- Extrae de la columna  `'Born'` el año de nacimiento y genera una nueva columna denominada `'Year Born'`

In [17]:
df = pd.read_csv("../data/presidents.csv")

df.head()

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age
0,1,George Washington,"Feb 22, 1732[a]","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days"
1,2,John Adams,"Oct 30, 1735[a]","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days"
2,3,Thomas Jefferson,"Apr 13, 1743[a]","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days"
3,4,James Madison,"Mar 16, 1751[a]","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days"
4,5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days"

Columna para el nombre 'firstname'

In [18]:
df['First name'] = df['President']
df['First name'] = df['First name'].replace('[ ].*', '', regex=True)

df['Last name'] = df['President']
df['Last name'] = df['Last name'].replace('.*[ ]', '', regex=True )

df.head()

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age,First name,Last name
0,1,George Washington,"Feb 22, 1732[a]","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George,Washington
1,2,John Adams,"Oct 30, 1735[a]","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days",John,Adams
2,3,Thomas Jefferson,"Apr 13, 1743[a]","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days",Thomas,Jefferson
3,4,James Madison,"Mar 16, 1751[a]","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days",James,Madison
4,5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days",James,Monroe

Eliminamos texto

In [20]:
df['Born_clean'] = df['Born'].str.extract(
    r'([A-Za-z]{3,9} \d{1,2}, \d{4})',
    expand=False
)

Convertimos Columnas

In [21]:
df['Born_dt'] = pd.to_datetime(df['Born_clean'], errors='coerce')
print(df[['Born', 'Born_clean', 'Born_dt']].head(15))

               Born    Born_clean    Born_dt
0   Feb 22, 1732[a]  Feb 22, 1732 1732-02-22
1   Oct 30, 1735[a]  Oct 30, 1735 1735-10-30
2   Apr 13, 1743[a]  Apr 13, 1743 1743-04-13
3   Mar 16, 1751[a]  Mar 16, 1751 1751-03-16
4      Apr 28, 1758  Apr 28, 1758 1758-04-28
5      Jul 11, 1767  Jul 11, 1767 1767-07-11
6      Mar 15, 1767  Mar 15, 1767 1767-03-15
7       Dec 5, 1782   Dec 5, 1782 1782-12-05
8       Feb 9, 1773   Feb 9, 1773 1773-02-09
9      Mar 29, 1790  Mar 29, 1790 1790-03-29
10      Nov 2, 1795   Nov 2, 1795 1795-11-02
11     Nov 24, 1784  Nov 24, 1784 1784-11-24
12      Jan 7, 1800   Jan 7, 1800 1800-01-07
13     Nov 23, 1804  Nov 23, 1804 1804-11-23
14     Apr 23, 1791  Apr 23, 1791 1791-04-23

Extraemos Año de Nacimiento

In [22]:
df['Year Born'] = (
    df['Born']
      .astype(str)
      .str.extract(r'(\d{4})', expand=False)
      .astype(int)
)

print(df[['Born', 'Year Born']].head(10))

              Born  Year Born
0  Feb 22, 1732[a]       1732
1  Oct 30, 1735[a]       1735
2  Apr 13, 1743[a]       1743
3  Mar 16, 1751[a]       1751
4     Apr 28, 1758       1758
5     Jul 11, 1767       1767
6     Mar 15, 1767       1767
7      Dec 5, 1782       1782
8      Feb 9, 1773       1773
9     Mar 29, 1790       1790